### PR TITLE
feat: implement warning message on download with experimental versions (also added cfbw+ap)

### PR DESCRIPTION
**Pull request by FoxtrotSierra6829**
## Summary of Changes
- Implement download for 'Custom FBW+AP'
- Add warning message when selecting experimental version

## Screenshots (if necessary)
grafik
grafik

Discord username (if different from GitHub):
Foxtrot Sierra#6420

### CODE REVIEW

**Comment by Snapmatics** [comment]
Could you make the width of the box bigger?

**Comment by FoxtrotSierra6829** [comment]
Height is dependent on how long the text is. If the one fits, the other won't anymore. It's centered vertically, as long as it is shorter than the frame. I can make it bigger, sure, but any other text will not have the same borders. If I take that centering away, and manually configure a 'centering' for this text, I will automatically remove space where text can be displayed.

**Comment by Snapmatics** [comment]
> 
> 
> Height is dependent on how long the text is. If the one fits, the other won't anymore. It's centered vertically, as long as it is shorter than the frame. I can make it bigger, sure, but any other text will not have the same vertical borders. If I take that centering away, and manually configure a 'centering' for this text, I will automatically remove space where text can be displayed.

I meant something like this if you want me to be more specific 
image

**Comment by Benjozork** [comment]
@Snapmatics to comment on that design, I would avoid centering the button, and reduce the border-radius.

**Comment by omarsmak** [comment]
Does it make sense to add the guidelines from here as well https://github.com/flybywiresim/a32nx/tree/autopilot/docs ?

**Comment by MisterChocker** [comment]
Well, shouldn't we also give the user an "abort" button, so if he doesn't want to continue?

**Comment by FoxtrotSierra6829** [comment]
> 
> 
> Well, shouldn't we also give the user an "abort" button, so if he doesn't want to continue?

wilco

**Review by ZigTag — APPROVED** [review]

**Pull request merged**
