### PR TITLE
feat: add link to FBW Documentations

### PR DESCRIPTION
**Pull request by GhostEagle68**
Fixes #[issue_no]

## Summary of Changes
Added FBW Logo with a caption that directs people to FBW Documentations

## Screenshots (if necessary)
Before
image

After
image

## Additional context
Discord username (if different from GitHub):

### CODE REVIEW

**Comment by GhostEagle68** [comment]
> I don't think this is the way to go, first of all, I don't see how the users will even know the link is clickable, also, if it is just the flybywire logo then I'd personally expect it to lead to the homepage, not the documentation.

Noted. I'll look at fixing it up later today and tomorrow 👍

**Comment by GhostEagle68** [comment]
Image to go along with 981e825. The icon still TBD, one in the pic is temporary

image

**Comment by Benjozork** [comment]
This needs a new visual design. This icon is inconsistent with the rest of the icons used in the app, and the overall layout of the button also is.

Also, this should not be placed on the A32NX page. It should be somehow general to the FBW section.

**Comment by GhostEagle68** [comment]
In reference to bdeb21d:

-Changed Link to Beginner Guide for A32NX
-Removed all icons and made it text instead
image

**Comment by ZigTag** [comment]
> It would be far better to put a book icon on the flybywire tab or somewhere at the top of each selection I feel.

Yes, if it's made to look like an icon, then it can be accomplished well

**Comment by ErickSharp** [comment]
Will be coming in version 3.

**Pull request closed without merging**
