### PR TITLE
feat: added issue creation button

### LINKED ISSUE #108: [REQUEST] Report aircraft issues from the installer
**Is your feature request related to a problem? Please describe.**
People using the listed versions in the installer as a reference for what is installed without even showing what is currently installed.

**Describe the feature you'd like to see implemented**
A bug report feature that provides information about the currently installed version.

**Additional context**

Discord username (if different from GitHub): nistei#1362

### PR DESCRIPTION
**Pull request by armankir**
Co-Authored-By: ZigTag <17077422+ZigTag@users.noreply.github.com>

Fixes #108 

## Summary of Changes
We added a report issue button at the top right corner of the installer, the button will open the A32NX issue report page on GitHub.

## Screenshots (if necessary)
Capture

Discord username (if different from GitHub): Arman#5297

### CODE REVIEW

**Review by ZigTag — APPROVED** [review]
LGTM

**Comment by FoxtrotSierra6829** [comment]
Could you add an entry to the changelog?

**Comment by armankir** [comment]
> Could you add an entry to the changelog?

Yep doing it now sorry.

**Comment by armankir** [comment]
All set now.

**Pull request merged**
