### PR TITLE
refactor: Update buttons and icons on sidebar

### PR DESCRIPTION
**Pull request by GhostEagle68**
Fixes #[issue_no]

## Summary of Changes
Added missing buttons and new icons for the sidebar

## Screenshots (if necessary)
Dark: 
image
Light: 
image

## Additional context

Discord username (if different from GitHub): GhostEagle68#0030

### CODE REVIEW

**Comment by ErickSharp** [comment]
Hey, can you update the icons for the synaptic page as well?

**Comment by GhostEagle68** [comment]
> Hey, can you update the icons for the synaptic page as well?

Done

**Comment by ErickSharp** [comment]
On the flybywire page, put website at the bottom like for synaptic and put discord and twitter together.

**Comment by GhostEagle68** [comment]
> On the flybywire page, put website at the bottom like for synaptic and put discord and twitter together.

done

**Review by ErickSharp — APPROVED** [review]

**Pull request merged**
