### PR TITLE
General improvements + Add Redux

### PR DESCRIPTION
**Pull request by ilyeshammadi**
## Summary of Changes

**What has been done:**
- Add `webpack` alias for `renderer`, `main` and `common`
- Update file structure to match Electron application patterns
- Refactor states in Aircraft component

## Additional context

Discord username (if different from GitHub):

### CODE REVIEW

**Review by ZigTag — APPROVED** [review]
LGTM

**Comment by nistei** [comment]
`isDownloading` should be a global state. When switching tabs to home or another mod the state gets lost and the loading bar won't show up again.

**Comment by ilyeshammadi** [comment]
> `isDownloading` should be a global state. When switching tabs to home or another mod the state gets lost and the loading bar won't show up again.

You're right, I follow-up with more changes by using React store options, context, or something else in order to fix. The download of each mod is tied to the aircraft page and not the global App that's why I believe it should not be there but in a local store for that component.

**Comment by nistei** [comment]
After pressing cancel the button does not reset
image

**Comment by ilyeshammadi** [comment]
> After pressing cancel the button does not reset
> image

Good catch, should be fixed now.

**Comment by nistei** [comment]
Now, this happens when switching tabs while downloading. The second button disappears after a few seconds.
image

**Comment by ilyeshammadi** [comment]
@nistei can you check again for me, with the latest commit in this PR?

**Comment by nistei** [comment]
This issue isn't happening anymore.
> After pressing cancel the button does not reset
> image

But the fix introduced a new issue. 
> Now, this happens when switching tabs while downloading. The second button disappears after a few seconds.
> image

**Pull request merged**
