### PR TITLE
Prevent user from selecting text & dragging images

### LINKED ISSUE #56: [REQUEST] Make text not selectable
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Currently you can select text on each page, which doesn't make sense to allow. It would make more sense to disable the ability to select text

**Additional context**

Discord username (if different from GitHub):

### LINKED ISSUE #60: [REQUEST] Make Image Elements Undraggable
**Is your feature request related to a problem? Please describe.**

Yes, the images are currently able to be dragged instead of "baked" onto the page. This consists of the drawings of the a320 and a380 on the installer tabs, and the engine variant drawing. 

**Describe the feature you'd like to see implemented**

Make image elements undraggable by the user.

**Additional context**

Discord username (if different from GitHub): Erick [Z-6]#6484

### PR DESCRIPTION
**Pull request by FoxtrotSierra6829**
Fixes #56
Fixes #60 

Discord username (if different from GitHub):
Foxtrot Sierra#6420

### CODE REVIEW

**Comment by nistei** [comment]
Is there a reason `-webkit-user-drag: none;` is not set globally for `img`?

**Comment by FoxtrotSierra6829** [comment]
> 
> 
> Is there a reason `-webkit-user-drag: none;` is not set globally for `img`?

Good question actually, but if you do that, you cannot drag the window anymore. Not sure why tho.

**Comment by nistei** [comment]
> > Is there a reason `-webkit-user-drag: none;` is not set globally for `img`?
> 
> Good question actually, but if you do that, you cannot drag the window anymore. Not sure why tho.

I just tested this and it works perfectly fine.
image

**Comment by FoxtrotSierra6829** [comment]
> 
> I just tested this and it works perfectly fine.

Tried to reproduce the issue that I had the first time I tried that, and it doesn't occur anymore. Probably did something wrong elsewhere. Files are now changed to global usage.

**Comment by nistei** [comment]
LGTM

**Pull request merged**
