### PR TITLE
fix: Avoid caching of config file

### PR DESCRIPTION
**Pull request by frankkopp**
## Summary of Changes
As it sometimes takes forever for users to see new configs we should make sure the config file is not cached. 

I tried with a http header which didn't work. So added a cache-killer parameter. 

## Additional context
https://discord.com/channels/738864299392630914/846470774361161808/1307387181605847120

Discord username (if different from GitHub): cdr_maverick

### CODE REVIEW

**Comment by Revyn112** [comment]
@frankkopp How you've tried to set the header?
Just wondering, as we are using the cache control within the fetch options and have no problems with cached configuration files so far.

```return await fetch(url, { cache: "no-store" })```

**Review by pdellaert — APPROVED** [review]

**Comment by pdellaert** [comment]
If the `cache: "no-store"` works, I'd prefer that, as it is a cleaner approach.

**Comment by frankkopp** [comment]
> @frankkopp How you've tried to set the header?
> 
> Just wondering, as we are using the cache control within the fetch options and have no problems with cached configuration files so far.
> 
> 
> 
> ```return await fetch(url, { cache: "no-store" })```
> 
> 
> 
> https://github.com/headwindsim/installer/blob/a2087477e5391dd2c33b90d453e3ef95fda31d1f/src/renderer/utils/InstallerConfiguration.ts#L406

Can try that. But I'm rather sure it had this in it as well.

**Comment by FoxtrotSierra6829** [comment]
> If the `cache: "no-store"` works, I'd prefer that, as it is a cleaner approach. But not sure how aggressive Cloudflare caching can be.

The issue is not about the caching in Cloudflare's CDN, but the Installer's dynamic Chromium disk cache.

**Comment by frankkopp** [comment]
I tested a few more headers - but I think they do not influence the internal cache of the Chromium cache.
Only the cache-killer seem to work.

```ts
return await fetch(url, { cache: 'no-store' })
```
or these:

```ts
return await fetch(url, { headers: { 'Cache-Control': 'no-store, no-cache, must-revalidate, max-age=0, private' } })
``` 

The server (CloudFlare) seems to also override these headers in its response:
image

So - it seems only the cache-killer param works.

**Pull request merged**
