### PR TITLE
feat: implemented auto update

### LINKED ISSUE #105: [REQUEST] Auto download/install
**Is your feature request related to a problem? Please describe.**
have an option to automatically download the latest version

**Describe the feature you'd like to see implemented**
If autoupdate is ticked, when the program is launched, it will check for an update, as it does now, then will automatically download the update and install, as many users will always want to be on the latest update

**Additional context**
could potentially be a message box that opens the first time the program is launched, with an option for the user to tick it

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by ZigTag**
Fixes #105

## Screenshots (if necessary)

image
image

## Additional context

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by Snapmatics** [comment]
I would suggest a toggle to keep things organized because we will probably add more things in the settings.

**Comment by ZigTag** [comment]
It is a toggle

**Comment by Benjozork** [comment]
Probably needs to changed to work with fragmenter

**Comment by ZigTag** [comment]
> 
> 
> Probably needs to changed to work with fragmenter

standby

**Comment by ZigTag** [comment]
This definitely needs testing, no idea if it works.

**Comment by FoxtrotSierra6829** [comment]
Feature needs to be entirely redone to be working with multiple addons

**Pull request closed without merging**
